created WeatherForecast.tsx
waldbrandpraevention/frontend pull request #81
Opened 2023-01-10 14:28 UTC by tagzyassi

einmal drüberschauen pls xD
Das Stylen geht bestimmt einfacher als mit den ganzen <div> (ist glaub ich bisschen unübersichtlich ^^) - also könnt da gerne noch was dran ändern

2023-01-10 15:24 UTC, Jade2508 requested changes
bitte nicht so stylen nimm bootstap syles mit className="d-flex" zum Beispiel
https://getbootstrap.com/docs/4.0/utilities/flex/
oder wenn unbedingt sein muss erstell ein sylend Componenet 
const MyTile = styled(Tile )`
    height: 100%;
    width: 100%;

dann hastdu auch kein problem von scaling 
![image](https://user-images.githubusercontent.com/20494618/211591509-33f35864-a444-4dcb-b0d8-befd4a7b62a0.png)

2023-01-10 21:05 UTC, adrianschubek commented on src/components/tiles/WeatherForecast.tsx
> +
Das kann man so direkt nicht machen. Angenommen `today` ist der `31.01.2023` dann wäre bei dir `tomorrow` der `32.01.2023`. Kann man bspw [so ](https://www.tutorialrepublic.com/faq/how-to-add-days-to-current-date-in-javascript.php)lösen

2023-01-10 22:31 UTC, adrianschubek commented
Bin grade dabei die Karte und Wetterkachel zu synchronisieren und die DWD API anzubinden. Close den PR daher hier erstmal.

2023-01-11 13:18 UTC, adrianschubek commented
Hab die API eingebunden. @tagzyassi kannst gerne probieren, damit die Wettervorhersage Kachel zu designen

2023-01-13 15:20 UTC, adrianschubek approved these changes

2023-01-14 17:08 UTC, Jade2508 approved these changes

2023-01-14 17:08 UTC, merged